[[Xorg_libXi]]
arch = "aarch64"
git-tree-sha1 = "dfad96fb1124df40a9d5b65664f47da6aec25b88"
libc = "musl"
os = "linux"

    [[Xorg_libXi.download]]
    sha256 = "3a4d95941a1a3d1473ff0f7db45d4ccddd9d1cb31e9cffe6a5b298c6c2f888c2"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXi_jll.jl/releases/download/Xorg_libXi-v1.7.10+1/Xorg_libXi.v1.7.10.aarch64-linux-musl.tar.gz"
[[Xorg_libXi]]
arch = "aarch64"
git-tree-sha1 = "e4761e6a3e38d617c6b3b0d02652e0b6fc736aaa"
libc = "glibc"
os = "linux"

    [[Xorg_libXi.download]]
    sha256 = "3cb50fef96e74e8adb961a0047c7f1cf7c144d8f7573275f993b39bcc1564cbc"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXi_jll.jl/releases/download/Xorg_libXi-v1.7.10+1/Xorg_libXi.v1.7.10.aarch64-linux-gnu.tar.gz"
[[Xorg_libXi]]
arch = "x86_64"
git-tree-sha1 = "bb4309b511c155da5c49e10ed37a7d0b191c0ea9"
libc = "glibc"
os = "linux"

    [[Xorg_libXi.download]]
    sha256 = "96bf455e88b94240ae844c37de8892752dc99d685cd501ccc5f0f7d47d6997f4"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXi_jll.jl/releases/download/Xorg_libXi-v1.7.10+1/Xorg_libXi.v1.7.10.x86_64-linux-gnu.tar.gz"
[[Xorg_libXi]]
arch = "powerpc64le"
git-tree-sha1 = "a23781f396dcd9b7d4cd6c7887ce9121d951e4c2"
libc = "glibc"
os = "linux"

    [[Xorg_libXi.download]]
    sha256 = "666b0eb826637ea39003224ca70f7d003539293ae7ecbd35c82aa42b8b4b6440"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXi_jll.jl/releases/download/Xorg_libXi-v1.7.10+1/Xorg_libXi.v1.7.10.powerpc64le-linux-gnu.tar.gz"
[[Xorg_libXi]]
arch = "x86_64"
git-tree-sha1 = "fef2e4cbcc22c6737100e584e71a5a9530b01388"
os = "freebsd"

    [[Xorg_libXi.download]]
    sha256 = "36db1d0ed95a1a94f4161dd1544e33ee8edb84be09cdd7c9d2299f04ab9c2aac"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXi_jll.jl/releases/download/Xorg_libXi-v1.7.10+1/Xorg_libXi.v1.7.10.x86_64-unknown-freebsd11.1.tar.gz"
[[Xorg_libXi]]
arch = "i686"
git-tree-sha1 = "6a73ab760314753aa9791a6d0f042b9fd001e681"
libc = "glibc"
os = "linux"

    [[Xorg_libXi.download]]
    sha256 = "f22b3dfdc20285d2e03c26cba1a0edb3fcd83d721982ea61328fe98d333082dc"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXi_jll.jl/releases/download/Xorg_libXi-v1.7.10+1/Xorg_libXi.v1.7.10.i686-linux-gnu.tar.gz"
[[Xorg_libXi]]
arch = "i686"
git-tree-sha1 = "bd661bc8e3c4070fb722a13e0bbddf1a1c5899fd"
libc = "musl"
os = "linux"

    [[Xorg_libXi.download]]
    sha256 = "51a8feb93bb5c8045f69fede043038ae8daf16ee4b5b729967e7f2fa95e9e925"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXi_jll.jl/releases/download/Xorg_libXi-v1.7.10+1/Xorg_libXi.v1.7.10.i686-linux-musl.tar.gz"
[[Xorg_libXi]]
arch = "armv7l"
git-tree-sha1 = "0ebb1b76e3f0a9ce3afe82bc534f61ace5e7398e"
libc = "glibc"
os = "linux"

    [[Xorg_libXi.download]]
    sha256 = "7e52dddd032a871ea44826974b0198734d7c793650eac0fd7fd05c72d9bc0f2c"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXi_jll.jl/releases/download/Xorg_libXi-v1.7.10+1/Xorg_libXi.v1.7.10.armv7l-linux-gnueabihf.tar.gz"
[[Xorg_libXi]]
arch = "x86_64"
git-tree-sha1 = "462ceb5ab9c13ac646767f4f70ce76b02331f1d8"
libc = "musl"
os = "linux"

    [[Xorg_libXi.download]]
    sha256 = "d72b6e0a42126b51867dd07a3e66f36adb7029a5ac24a8d841b9c029898cfab1"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXi_jll.jl/releases/download/Xorg_libXi-v1.7.10+1/Xorg_libXi.v1.7.10.x86_64-linux-musl.tar.gz"
[[Xorg_libXi]]
arch = "armv7l"
git-tree-sha1 = "ff6559af582c4e05f2c59d9d91365e8400b053e5"
libc = "musl"
os = "linux"

    [[Xorg_libXi.download]]
    sha256 = "212bfb273a9ed5bb8fb93b03d0f45661d6af40059699e93635585f597b3e80cf"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXi_jll.jl/releases/download/Xorg_libXi-v1.7.10+1/Xorg_libXi.v1.7.10.armv7l-linux-musleabihf.tar.gz"
